{
    "fp16": {
        "enabled": false
    },
    "bf16": {
        "enabled": true
    },
    "train_micro_batch_size_per_gpu": 48,
    "train_batch_size": "auto",
    "gradient_accumulation_steps": 1,
    "zero_optimization": {
        "stage": 1,
        "allgather_partitions": true,
        "allgather_bucket_size": 1e8,
        "reduce_scatter": true,
        "reduce_bucket_size": 1e8,
        "overlap_comm": true,
        "contiguous_gradients": true,
        "cpu_offload": false
    },
    "gradient_clipping": 1.0,
    "steps_per_print": 100
}